src/Entity/Participant.php
<?php

namespace App\Entity;

use App\Repository\ParticipantRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ParticipantRepository::class)]
class Participant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'participants')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Discussion $discussion = null;

    #[ORM\ManyToOne(inversedBy: 'participants')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_received = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_read = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDiscussion(): ?Discussion
    {
        return $this->discussion;
    }

    public function setDiscussion(?Discussion $discussion): self
    {
        $this->discussion = $discussion;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDateReceived(): ?\DateTimeInterface
    {
        return $this->date_received;
    }

    public function setDateReceived(?\DateTimeInterface $date_received): self
    {
        $this->date_received = $date_received;

        return $this;
    }

    public function getDateRead(): ?\DateTimeInterface
    {
        return $this->date_read;
    }

    public function setDateRead(?\DateTimeInterface $date_read): self
    {
        $this->date_read = $date_read;

        return $this;
    }
}

src/Form/ParticipantType.php
<?php

namespace App\Form;

use App\Entity\Participant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ParticipantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_received')
            ->add('date_read')
            ->add('discussion')
            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Participant::class,
        ]);
    }
}

src/Controller/ParticipantController.php
<?php

namespace App\Controller;

use App\Entity\Participant;
use App\Form\ParticipantType;
use App\Repository\ParticipantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/participant')]
class ParticipantController extends AbstractController
{
    #[Route('/', name: 'app_participant_index', methods: ['GET'])]
    public function index(ParticipantRepository $participantRepository): Response
    {
        return $this->render('participant/index.html.twig', [
            'participants' => $participantRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_participant_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ParticipantRepository $participantRepository): Response
    {
        $participant = new Participant();
        $form = $this->createForm(ParticipantType::class, $participant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $participantRepository->add($participant, true);

            return $this->redirectToRoute('app_participant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('participant/new.html.twig', [
            'participant' => $participant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_participant_show', methods: ['GET'])]
    public function show(Participant $participant): Response
    {
        return $this->render('participant/show.html.twig', [
            'participant' => $participant,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_participant_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Participant $participant, ParticipantRepository $participantRepository): Response
    {
        $form = $this->createForm(ParticipantType::class, $participant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $participantRepository->add($participant, true);

            return $this->redirectToRoute('app_participant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('participant/edit.html.twig', [
            'participant' => $participant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_participant_delete', methods: ['POST'])]
    public function delete(Request $request, Participant $participant, ParticipantRepository $participantRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$participant->getId(), $request->request->get('_token'))) {
            $participantRepository->remove($participant, true);
        }

        return $this->redirectToRoute('app_participant_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/participant/_delete_form.html.twig
<form method="post" action="{{ path('app_participant_delete', {'id': participant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ participant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/participant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/participant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Participant{% endblock %}

{% block body %}
    <h1>Edit Participant</h1>

    {{ include('participant/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_participant_index') }}">back to list</a>

    {{ include('participant/_delete_form.html.twig') }}
{% endblock %}

templates/participant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Participant index{% endblock %}

{% block body %}
    <h1>Participant index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_received</th>
                <th>Date_read</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for participant in participants %}
            <tr>
                <td>{{ participant.id }}</td>
                <td>{{ participant.dateReceived ? participant.dateReceived|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ participant.dateRead ? participant.dateRead|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_participant_show', {'id': participant.id}) }}">show</a>
                    <a href="{{ path('app_participant_edit', {'id': participant.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_participant_new') }}">Create new</a>
{% endblock %}

templates/participant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Participant{% endblock %}

{% block body %}
    <h1>Create new Participant</h1>

    {{ include('participant/_form.html.twig') }}

    <a href="{{ path('app_participant_index') }}">back to list</a>
{% endblock %}

templates/participant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Participant{% endblock %}

{% block body %}
    <h1>Participant</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ participant.id }}</td>
            </tr>
            <tr>
                <th>Date_received</th>
                <td>{{ participant.dateReceived ? participant.dateReceived|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_read</th>
                <td>{{ participant.dateRead ? participant.dateRead|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_participant_index') }}">back to list</a>

    <a href="{{ path('app_participant_edit', {'id': participant.id}) }}">edit</a>

    {{ include('participant/_delete_form.html.twig') }}
{% endblock %}