src/Entity/Discussion.php
<?php

namespace App\Entity;

use App\Repository\DiscussionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DiscussionRepository::class)]
class Discussion
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_created = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\ManyToOne(inversedBy: 'discussions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\OneToMany(mappedBy: 'discussion', targetEntity: Message::class, orphanRemoval: true)]
    private Collection $messages;

    #[ORM\OneToMany(mappedBy: 'discussion', targetEntity: Participant::class)]
    private Collection $participants;

    #[ORM\ManyToOne(inversedBy: 'discussions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
        $this->participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setDiscussion($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getDiscussion() === $this) {
                $message->setDiscussion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Participant>
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants->add($participant);
            $participant->setDiscussion($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        if ($this->participants->removeElement($participant)) {
            // set the owning side to null (unless already changed)
            if ($participant->getDiscussion() === $this) {
                $participant->setDiscussion(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
    public function __toString(){
        return $this-> getTitle(); // Remplacer champ par une propriété "string" de l'entité
    }
}

src/Form/DiscussionType.php
<?php

namespace App\Form;

use App\Entity\Discussion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DiscussionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_created')
            ->add('title')
            ->add('author')
            ->add('category')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Discussion::class,
        ]);
    }
}

src/Controller/DiscussionController.php
<?php

namespace App\Controller;

use App\Entity\Discussion;
use App\Form\DiscussionType;
use App\Repository\DiscussionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/discussion')]
class DiscussionController extends AbstractController
{
    #[Route('/', name: 'app_discussion_index', methods: ['GET'])]
    public function index(DiscussionRepository $discussionRepository): Response
    {
        return $this->render('discussion/index.html.twig', [
            'discussions' => $discussionRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_discussion_new', methods: ['GET', 'POST'])]
    public function new(Request $request, DiscussionRepository $discussionRepository): Response
    {
        $discussion = new Discussion();
        $form = $this->createForm(DiscussionType::class, $discussion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $discussionRepository->add($discussion, true);

            return $this->redirectToRoute('app_discussion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('discussion/new.html.twig', [
            'discussion' => $discussion,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_discussion_show', methods: ['GET'])]
    public function show(Discussion $discussion): Response
    {
        return $this->render('discussion/show.html.twig', [
            'discussion' => $discussion,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_discussion_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Discussion $discussion, DiscussionRepository $discussionRepository): Response
    {
        $form = $this->createForm(DiscussionType::class, $discussion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $discussionRepository->add($discussion, true);

            return $this->redirectToRoute('app_discussion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('discussion/edit.html.twig', [
            'discussion' => $discussion,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_discussion_delete', methods: ['POST'])]
    public function delete(Request $request, Discussion $discussion, DiscussionRepository $discussionRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$discussion->getId(), $request->request->get('_token'))) {
            $discussionRepository->remove($discussion, true);
        }

        return $this->redirectToRoute('app_discussion_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/discussion/_delete_form.html.twig
<form method="post" action="{{ path('app_discussion_delete', {'id': discussion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ discussion.id) }}">
    <button class="btn">Delete</button>
</form>

templates/discussion/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/discussion/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Discussion{% endblock %}

{% block body %}
    <h1>Edit Discussion</h1>

    {{ include('discussion/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_discussion_index') }}">back to list</a>

    {{ include('discussion/_delete_form.html.twig') }}
{% endblock %}

templates/discussion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Discussion index{% endblock %}

{% block body %}
    <h1>Discussion index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_created</th>
                <th>Title</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for discussion in discussions %}
            <tr>
                <td>{{ discussion.id }}</td>
                <td>{{ discussion.dateCreated ? discussion.dateCreated|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ discussion.title }}</td>
                <td>
                    <a href="{{ path('app_discussion_show', {'id': discussion.id}) }}">show</a>
                    <a href="{{ path('app_discussion_edit', {'id': discussion.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_discussion_new') }}">Create new</a>
{% endblock %}

templates/discussion/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Discussion{% endblock %}

{% block body %}
    <h1>Create new Discussion</h1>

    {{ include('discussion/_form.html.twig') }}

    <a href="{{ path('app_discussion_index') }}">back to list</a>
{% endblock %}

templates/discussion/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Discussion{% endblock %}

{% block body %}
    <h1>Discussion</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ discussion.id }}</td>
            </tr>
            <tr>
                <th>Date_created</th>
                <td>{{ discussion.dateCreated ? discussion.dateCreated|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ discussion.title }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_discussion_index') }}">back to list</a>

    <a href="{{ path('app_discussion_edit', {'id': discussion.id}) }}">edit</a>

    {{ include('discussion/_delete_form.html.twig') }}
{% endblock %}